services:
  - type: web
    name: crypto-edge
    env: docker
    dockerfilePath: Dockerfile.app
    port: 8501
    envVars:
      - key: WAREHOUSE_MODE
        value: bigquery
      - key: GCP_PROJECT_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
